import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
    inputAreaContainer: {
      flex: 1,
      alignItems: 'center',
    },
    input: {
      height: 40,
      width: 300,
      margin: 12,
      borderRadius: 50,
      padding: 10,
      backgroundColor: '#D3D3D3',
    },
    headerText: {
      color: '#003A67',
      fontSize: Dimensions.get('window').width/20,
      fontWeight: '800',
      textAlign: 'center',
      textAlignVertical: 'center',
      alignSelf: 'flex-start',
      paddingLeft: (Dimensions.get('window').width)/60,
    },
    subtext: {
      color: '#003A67',
      fontSize: Dimensions.get('window').width/30,
      textAlign: 'center',
      textAlignVertical: 'center',
      alignSelf: 'center',
    },
    backBtnText: {
      color: '#003A67',
      fontSize: Dimensions.get('window').width/30,
      textAlign: 'center',
      textAlignVertical: 'center',
      alignSelf: 'flex-start',
    },
    reporttext: {
      flex: 1,
      alignSelf: 'flex-start',
      color: '#003A67',
      fontSize: Dimensions.get('window').width/25,
      textAlign: 'center',
      textAlignVertical: 'center',
      marginTop: (Dimensions.get('window').height)/60,
    },
    datetext: {
      flex: 1,
      alignSelf: 'flex-end',
      color: '#003A67',
      fontSize: Dimensions.get('window').width/30,
      textAlign: 'center',
      textAlignVertical: 'center',
    },
    titlecontainer: {
      alignSelf: 'flex-start',
      backgroundColor: '#9AD3FF',
    },
    footercontainer: {
      width: Dimensions.get('window').width/1,
      alignSelf: 'center',
      flexDirection: "row",
      backgroundColor: '#fff',
    },
    backButton: {
      justifyContent: 'center', 
      alignItems: 'center',
      width: Dimensions.get('window').width/3,
      height: Dimensions.get('window').width/10,
      marginLeft: (Dimensions.get('window').width)/60,
    },
    pdfButton: {
      justifyContent: 'center', 
      alignItems: 'center',
      width: Dimensions.get('window').width/2,
      height: Dimensions.get('window').width/10,
    },
    reportContainer: {
      flex: 1,
      alignSelf: 'flex-start',
      width: Dimensions.get('window').width/1,
      // borderRadius: 5,
      marginLeft: (Dimensions.get('window').width)/30,
      marginRight: (Dimensions.get('window').width)/30,
      marginBottom: (Dimensions.get('window').height)/40,
      borderColor: '#003A67',
      borderWidth: 3,
      backgroundColor: '#fff',
    },
    formcontainer: {
      flex: 1,
      alignSelf: 'flex-start',
      width: Dimensions.get('window').width/1,
      paddingLeft: (Dimensions.get('window').width)/30,
      paddingRight: (Dimensions.get('window').width)/30,
      paddingBottom: (Dimensions.get('window').height)/40,
      paddingTop: (Dimensions.get('window').height)/40,
      borderBottomColor: "rgba(21,21,21,0.2)",
      borderBottomWidth: 2,
      backgroundColor: '#fff',
    },
});