import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
    inputAreaContainer: {
      flex: 1,
      alignItems: 'center',
    },
    input: {
      height: 40,
      width: 300,
      margin: 12,
      borderRadius: 50,
      padding: 10,
      backgroundColor: '#D3D3D3',
    },
    headerText: {
      color: '#003A67',
      fontSize: Dimensions.get('window').width/16,
      fontWeight: '800',
      textAlign: 'center',
      textAlignVertical: 'center',
      alignSelf: 'flex-start',
    },
    text: {
      color: '#003A67',
      fontSize: Dimensions.get('window').width/20,
      fontWeight: '700',
      textAlign: 'center',
      textAlignVertical: 'center',
      alignSelf: 'flex-start',
    },
    subtext: {
      color: '#003A67',
      fontSize: Dimensions.get('window').width/30,
      textAlign: 'center',
      textAlignVertical: 'center',
      alignSelf: 'center',
    },
    reporttext: {
      flex: 1,
      alignSelf: 'flex-start',
      color: '#003A67',
      fontSize: Dimensions.get('window').width/20,
      fontWeight: '600',
      textAlign: 'center',
      textAlignVertical: 'center',
      marginTop: (Dimensions.get('window').height)/50,
      marginBottom: (Dimensions.get('window').height)/30,
    },
    datetext: {
      flex: 1,
      alignSelf: 'flex-end',
      color: '#003A67',
      fontSize: Dimensions.get('window').width/30,
      textAlign: 'center',
      textAlignVertical: 'center',
    },
    bottomButton: {
      width: Dimensions.get('window').width/1.5,
      height: Dimensions.get('window').width/10,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 20,
      backgroundColor: '#fff',
      marginTop: (Dimensions.get('window').height)/30,
      marginBottom: (Dimensions.get('window').height)/20,
    },
    titlecontainer: {
      alignSelf: 'flex-start',
      backgroundColor: '#9AD3FF',
      paddingLeft: (Dimensions.get('window').width)/30,
      marginBottom: (Dimensions.get('window').height)/300,
      marginTop: (Dimensions.get('window').height)/40,
    },
    footercontainer: {
      width: Dimensions.get('window').width/1,
      alignSelf: 'center',
      flexDirection: "row",
      backgroundColor: '#fff',
    },
    pdfButton: {
      justifyContent: 'center', 
      alignItems: 'center',
      width: Dimensions.get('window').width/2,
      height: Dimensions.get('window').width/10,
    },
    reportContainer: {
      flex: 1,
      alignSelf: 'flex-start',
      width: Dimensions.get('window').width/1,
      // borderRadius: 5,
      borderTopColor: "rgba(21,21,21,0.2)",
      borderTopWidth: 3,
      borderBottomColor: "rgba(21,21,21,0.2)",
      borderBottomWidth: 3,
      backgroundColor: '#fff',
      marginTop: (Dimensions.get('window').height)/50,
    },
    formcontainer: {
      flexDirection: "column",
      paddingLeft: (Dimensions.get('window').width)/30,
      paddingRight: (Dimensions.get('window').width)/30,
      paddingBottom: (Dimensions.get('window').height)/40,
      paddingTop: (Dimensions.get('window').height)/40,
      borderBottomColor: "rgba(21,21,21,0.2)",
      borderBottomWidth: 2,
    },
});